package_reboot_if_required: true
packages:
  - qemu-guest-agent
runcmd:
  # Configure automatic updates
  - sed -i 's/\/\/Unattended-Upgrade::Automatic-Reboot-Time "02:00"/Unattended-Upgrade::Automatic-Reboot-Time "06:00"/' /etc/apt/apt.conf.d/50unattended-upgrades
  # Disable IPv6
  - sed -i 's/IPV6=yes/IPV6=no/' /etc/default/ufw
