apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: monitoring
spec:
  groups:
  - name: infrastructure
    rules:
    - alert: HostHighCpuLoad
      expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 50
      for: 5m
      labels:
        severity: warning
        namespace: monitoring
      annotations:
        summary: "Host CPU load is over 50%"
        description: "The host CPU load is at {{ $value }}% for more than 5 minutes. Instance: {{ $labels.instance }}"
    - alert: KubernetesPodCrashLooping
      expr: kube_pod_container_status_restarts_total > 5
      for: 0m
      labels:
        severity: critical
        namespace: monitoring
      annotations:
        summary: "Pod container is crash looping"
        description: "Pod {{ $labels.pod }} is crash looping."
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: custom-alertmanager
  namespace: monitoring
  # labels:
  #   app: kube-prometheus-stack
  #   release: monitoring
spec:
  route:
    receiver: "email"
    repeatInterval: 30m
    routes:
    - matchers:
      - name: alertname
        value: HostHighCpuLoad
    - matchers:
      - name: alertname
        value: KubernetesPodCrashLooping
      receiver: "email"
      repeatInterval: 10m
  receivers:
  - name: "email"
    emailConfigs:
    - to: "email"
      from: "email"
      smarthost: 'smtp.gmail.com:587'
      authUsername: "email"
      authIdentity: "email"
      authPassword:
        name: gmail-auth
        key: password



