name: nexus #will be used for network auto naming and image names
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
#    healthcheck:
#      test: curl http://localhost:8081/
#      interval: 10s
#      start_period: 5s
    volumes:
      - "data:/nexus-data" #Volume mapping for persistency
    ports:
      - "8081:8081"
      - "8082:8082" # Port for Docker repo
volumes:
  data: # It will prepend the project name