{
 "title": "Docker Containers Telegraf",
 "description": "Docker container metrics with Telegraph & Prometheus",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "container", "label": "Select container", "query": { "query": "label_values(container_name)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{container_name=~\"$container\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_container_mem_usage{container_name=~\"$container\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Runtimes",
   "type": "stat",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_container_status_uptime_ns{container_name=~\"$container\"} / 1000000",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Network RxTx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(docker_container_net_rx_bytes{container_name=~\"$container\"}[5m])",
     "legendFormat": "RX {{container_name}}"
    },
    {
     "expr": "rate(docker_container_net_tx_bytes{container_name=~\"$container\"}[5m]) * -1",
     "legendFormat": "TX {{container_name}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "docker_disk_usage_size_root_fs{container_name=~\"$container\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}