apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cartService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.cartService.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.cartService.name }}
    spec:
      containers:
      - name: {{ .Values.cartService.name }}
        image: {{ .Values.images.repository }}/{{ .Values.cartService.name }}:{{ .Chart.AppVersion }}
        ports:
        - containerPort: {{ .Values.cartService.port }}
        env:
        - name: PORT
          value: "7070"
        - name: REDIS_ADDR
          value: "{{ .Values.cartDatabase.name }}:6379"
        readinessProbe:
          initialDelaySeconds: 15
          grpc:
            port: {{ .Values.cartService.port }}
        livenessProbe:
          initialDelaySeconds: 15
          grpc:
            port: {{ .Values.cartService.port }}
        resources:
          {{- toYaml .Values.cartService.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cartService.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.cartService.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.cartService.port }}
      targetPort: {{ .Values.cartService.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cartDatabase.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.cartDatabase.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.cartDatabase.name }}
    spec:
      containers:
      - name: {{ .Values.cartDatabase.name }}
        image: redis:alpine
        ports:
        - containerPort: {{ .Values.cartDatabase.port }}
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.cartDatabase.port }}
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.cartDatabase.port }}
        resources:
          {{- toYaml .Values.cartDatabase.resources | nindent 10 }}
        volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cartDatabase.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.cartDatabase.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.cartDatabase.port }}
      targetPort: {{ .Values.cartDatabase.port }}