apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.adService.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.adService.name }}
    spec:
      containers:
      - name: {{ .Values.adService.name }}
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.2
        ports:
        - containerPort: {{ .Values.adService.port }}
        env:
        - name: PORT
          value: "9555"
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: {{ .Values.adService.port }}
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: {{ .Values.adService.port }}
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adService.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.adService.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.adService.port }}
      targetPort: {{ .Values.adService.port }}