apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cartService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.cartService.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.cartService.name }}
    spec:
      containers:
      - name: {{ .Values.cartService.name }}
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/{{ .Values.cartService.name }}:v0.10.2
        ports:
        - containerPort: {{ .Values.cartService.port }}
        env:
        - name: PORT
          value: "7070"
        - name: REDIS_ADDR
          value: "{{ .Values.cartDatabase.name }}:6379"
        readinessProbe:
          initialDelaySeconds: 15
          grpc:
            port: {{ .Values.cartService.port }}
        livenessProbe:
          initialDelaySeconds: 15
          grpc:
            port: {{ .Values.cartService.port }}
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cartService.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.cartService.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.cartService.port }}
      targetPort: {{ .Values.cartService.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cartDatabase.name }}
spec:
  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.cartDatabase.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.cartDatabase.name }}
    spec:
      containers:
      - name: {{ .Values.cartDatabase.name }}
        image: redis:alpine
        ports:
        - containerPort: {{ .Values.cartDatabase.port }}
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.cartDatabase.port }}
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: {{ .Values.cartDatabase.port }}
        resources:
          requests:
            cpu: 70m
            memory: 200Mi
          limits:
            cpu: 125m
            memory: 256Mi
        volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cartDatabase.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.cartDatabase.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.cartDatabase.port }}
      targetPort: {{ .Values.cartDatabase.port }}