apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.emailService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.emailService.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.emailService.name }}
    spec:
      containers:
      - name: {{ .Values.emailService.name }}
        image: {{ .Values.images.repository }}/{{ .Values.emailService.name }}:{{ .Chart.AppVersion }}
        ports:
        - containerPort: {{ .Values.emailService.port }}
        env:
        - name: PORT
          value: "8080"
        readinessProbe: # checks if app is ready/started to receive traffic
          periodSeconds: 5
          grpc:
            port: {{ .Values.emailService.port }}
        livenessProbe: # pings the container to check if container is available
          periodSeconds: 5
          grpc:
            port: {{ .Values.emailService.port }}
        resources:
          {{- toYaml .Values.emailService.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.emailService.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.emailService.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: {{ .Values.emailService.port }}