apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.emailService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.emailService.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.emailService.name }}
    spec:
      containers:
      - name: {{ .Values.emailService.name }}
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/{{ .Values.emailService.name }}:v0.10.2
        ports:
        - containerPort: {{ .Values.emailService.port }}
        env:
        - name: PORT
          value: "8080"
        readinessProbe: # checks if app is ready/started to receive traffic
          periodSeconds: 5
          grpc:
            port: {{ .Values.emailService.port }}
        livenessProbe: # pings the container to check if container is available
          periodSeconds: 5
          grpc:
            port: {{ .Values.emailService.port }}
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.emailService.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.emailService.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: {{ .Values.emailService.port }}