apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontendService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.frontendService.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.frontendService.name }}
    spec:
      containers:
      - name: {{ .Values.frontendService.name }}
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/{{ .Values.frontendService.name }}:v0.10.2
        ports:
        - containerPort: {{ .Values.frontendService.port }}
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice:5050"
        - name: AD_SERVICE_ADDR
          value: "adservice:9555"
        - name: SHOPPING_ASSISTANT_SERVICE_ADDR
          value: "shoppingassistantservice:80"
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: {{ .Values.frontendService.port }}
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-readiness-probe"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/_healthz"
            port: {{ .Values.frontendService.port }}
            httpHeaders:
            - name: "Cookie"
              value: "shop_session-id=x-liveness-probe"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.frontendService.name }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontendService.port }}