apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.recommendationService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.recommendationService.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.recommendationService.name }}
    spec:
      containers:
      - name: {{ .Values.recommendationService.name }}
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/{{ .Values.recommendationService.name }}:v0.10.2
        ports:
        - containerPort: {{ .Values.recommendationService.port }}
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: {{ .Values.recommendationService.port }}
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: {{ .Values.recommendationService.port }}
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.recommendationService.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.recommendationService.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.recommendationService.port }}
      targetPort: {{ .Values.recommendationService.port }}