name: homepage # Will be used for network auto naming and image names
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_VAR_PROXMOX_USER: ${PROXMOX_USER:?err} #exits with an error message containing err if VARIABLE is unset or empty in the environment.
      HOMEPAGE_VAR_PROXMOX_PASS: ${PROXMOX_PASS:?err}
    ports:
      - 3000:3000
    volumes:
      - data:/app/config # Make sure your local config directory exists
volumes:
  data: # It will prepend the project name
