---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Infrastructure:
    - Proxmox i7-6700:
        icon: proxmox.svg
        href: https://pve-i7-8700.lan:8006
        ping: 192.168.84.6
        #description: pve-critical
        #widget:
        #  type: proxmox
        #  url: https://pve.lan:8006
        #  username: {{HOMEPAGE_VAR_PROXMOX_USER}}
        #  password: {{HOMEPAGE_VAR_PROXMOX_PASS}}
    - Proxmox New:
        icon: proxmox.svg
        href: https://pve-new.lan:8006
        ping: 192.168.84.10
        #description: pve-new
    - Truenas Scale:
        icon: truenas.svg
        href: http://nas.lan
        ping: 192.168.84.11
        #description: pve1
    - Portainer Homelab:
        icon: portainer.svg
        href: https://homelab.lan:9443
        ping: 192.168.84.16
        description: homelab.lan
    - Portainer Hosting:
        icon: portainer.svg
        href: https://hosting-prod.lan:9443
        ping: 192.168.84.15
        description: hosting-prod.lan

- Networking:
    - Gateway Router:
        icon: openwrt.svg
        href: http://router.lan
        #description: OpenWRT OS
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.svg
        href: http://proxy.lan:81/login
        ping: 192.168.84.254
    - Adguard Home:
        icon: adguard-home.svg
        href: http://adguard.lan
        ping: 192.168.84.27
    - Unifi Site Manager:
        icon: unifi.svg
        href: https://unifi.ui.com

- Manage:
    - Home Assistant:
        icon: home-assistant.svg
        href: https://ha.repina.eu
        ping: https://ha.repina.eu
    - Frigate NVR:
        icon: frigate.svg
        href: http://frigate.lan:5000
        ping: 192.168.84.13
    - Nexus:
        icon: https://raw.githubusercontent.com/juronja/homelab-configs/main/Applications/Homepage/icons/sonatype-nexus.png
        href: http://homelab.lan:8081
        ping: 192.168.84.16
    - Jenkins:
        icon: jenkins.svg
        href: https://jenkins.repina.eu
        ping: https://jenkins.repina.eu

- Media:
    - Nextcloud:
        icon: nextcloud.svg
        href: https://nextcloud.repina.eu
        ping: https://nextcloud.repina.eu
    - Audiobookshelf:
        icon: audiobookshelf.svg
        href: https://audiobook.repina.eu
        ping: https://audiobook.repina.eu
    - Readarr:
        icon: readarr.svg
        href: http://nas.lan:30045
    - qBittorrent:
        icon: qbittorrent.svg
        href: http://nas.lan:30024
    - Prowlarr:
        icon: prowlarr.svg
        href: http://nas.lan:30050
    - Radarr:
        icon: radarr.svg
        href: http://nas.lan:30025
    - Sonarr:
        icon: sonarr.svg
        href: http://nas.lan:30027
    - Lidarr:
        icon: lidarr.svg
        href: http://nas.lan:30014
