---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Infrastructure:
    - Proxmox Old:
        icon: proxmox.svg
        href: https://pve-old.repina.eu:8006
        siteMonitor: https://pve-old.repina.eu:8006
        description: pve-old
        #widget:
        #  type: proxmox
        #  url: https://pve.repina.eu:8006
        #  username: {{HOMEPAGE_VAR_PROXMOX_USER}}
        #  password: {{HOMEPAGE_VAR_PROXMOX_PASS}}
    - Proxmox New:
        icon: proxmox.svg
        href: https://pve-new.repina.eu:8006
        siteMonitor: https://pve-new.repina.eu:8006
        description: pve-new
    - Truenas Scale:
        icon: truenas.svg
        href: http://nas.repina.eu
        siteMonitor: http://nas.repina.eu
        #description: pve1

- Networking:
    - Gateway Router:
        icon: openwrt.svg
        href: http://router.repina.eu
        description: OpenWRT OS
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.svg
        href: http://proxy.repina.eu:81/login
    - Unifi Site Manager:
        icon: unifi.svg
        href: https://unifi.ui.com
    - Pihole:
        icon: pi-hole.svg
        href: http://pihole.repina.eu/admin/login.php

- Manage:
    - Home Assistant:
        icon: home-assistant.svg
        href: http://ha.repina.eu
        #description: Homepage is 😎
    - Portainer:
        icon: portainer.svg
        href: https://portainer.repina.eu:9443
    - Jenkins:
        icon: jenkins.svg
        href: http://jenkins.repina.eu

- Media:
    - qBittorrent:
        icon: qbittorrent.svg
        href: http://nas.repina.eu:30024
        #description: Homepage is the best
    - Prowlarr:
        icon: prowlarr.svg
        href: http://nas.repina.eu:30050
        #description: Homepage is the best
    - Radarr:
        icon: radarr.svg
        href: http://nas.repina.eu:30025
        #description: Homepage is the best
    - Sonarr:
        icon: sonarr.svg
        href: http://nas.repina.eu:30027
        #description: Homepage is the best
    - Readarr:
        icon: readarr.svg
        href: http://nas.repina.eu:30045
        #description: Homepage is the best
    - Audiobookshelf:
        icon: audiobookshelf.svg
        href: http://audiobook.repina.eu
        #description: Homepage is the best
