---
# Icons library: https://github.com/homarr-labs/dashboard-icons

- Infrastructure:
    - Proxmox 9700:
        icon: proxmox.svg
        href: https://pve-9700.lan:8006
        ping: pve-9700.lan
    - Proxmox 4750g:
        icon: proxmox.svg
        href: https://pve-4750g.lan:8006
        ping: pve-4750g.lan
        #description: pve-critical
        #widget:
        #  type: proxmox
        #  url: https://pve.lan:8006
        #  username: {{HOMEPAGE_VAR_PROXMOX_USER}}
        #  password: {{HOMEPAGE_VAR_PROXMOX_PASS}}
    - Truenas:
        icon: truenas.svg
        href: http://nas.lan
        ping: nas.lan
    - Portainer | Homelab:
        icon: portainer.svg
        href: https://homelab.lan:9443
        ping: homelab.lan

- Networking:
    - Gateway Router:
        icon: openwrt.svg
        href: http://gateway.lan
    - Unifi Network Server:
        icon: unifi.svg
        href: https://unifi.lan:8443
        description: pernica
    - Adguard Home:
        icon: adguard-home.svg
        href: http://adguard.lan
    - WGDashboard:
        icon: wireguard.svg
        href: http://wireguard.lan:10086
        ping: wireguard.lan
    - Unifi Site Manager:
        icon: unifi.svg
        href: https://unifi.ui.com

- Tools:
    - Home Assistant:
        icon: home-assistant.svg
        href: https://ha.homelabtales.com
        ping: https://ha.homelabtales.com
    - Frigate NVR:
        icon: frigate.svg
        href: http://frigate.lan:5000
        ping: 192.168.84.13
    - Nexus:
        icon: https://raw.githubusercontent.com/juronja/homelab-configs/main/Applications/Homepage/icons/sonatype-nexus.png
        href: http://homelab.lan:8081
        ping: homelab.lan
    - Jenkins:
        icon: jenkins.svg
        href: https://jenkins.homelabtales.com
        ping: https://jenkins.homelabtales.com
    - Open WebUI:
        icon: open-webui.svg
        href: http://openwebui.lan:8080
        ping: openwebui.lan

- Media:
    - Audiobookshelf:
        icon: audiobookshelf.svg
        href: https://audiobook.homelabtales.com
        ping: https://audiobook.homelabtales.com
    - Readarr:
        icon: readarr.svg
        href: http://nas.lan:30045
        ping: nas.lan
    - qBittorrent:
        icon: qbittorrent.svg
        href: http://nas.lan:30024
        ping: nas.lan
    - Prowlarr:
        icon: prowlarr.svg
        href: http://nas.lan:30050
        ping: nas.lan
    - Radarr:
        icon: radarr.svg
        href: http://nas.lan:30025
        ping: nas.lan
    - Sonarr:
        icon: sonarr.svg
        href: http://nas.lan:30113
        ping: nas.lan
    - Lidarr:
        icon: lidarr.svg
        href: http://nas.lan:30071
        ping: nas.lan
