---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Servers:
    - Proxmox:
        icon: proxmox.svg
        href: https://pve.repina.eu:8006/
        #description: pve1
    - Truenas Scale:
        icon: truenas.svg
        href: http://nas.repina.eu/
        #description: pve1

- Manage:
    - Home Assistant:
        icon: home-assistant.svg
        href: http://ha.repina.eu:8123/
        #description: Homepage is 😎
    - Jenkins:
        icon: jenkins.svg
        href: http://192.168.84.25:8080/
    - Portainer:
        icon: portainer.svg
        href: https://portainer.repina.eu:9443/
    - Pihole:
        icon: pi-hole.svg
        href: http://pihole.repina.eu/admin/login.php
    - Unifi Site Manager:
        icon: unifi.svg
        href: https://unifi.ui.com/

- Media:
    - qBittorrent:
        icon: qbittorrent.svg
        href: http://nas.repina.eu:10095/
        #description: Homepage is the best
    - Prowlarr:
        icon: prowlarr.svg
        href: http://nas.repina.eu:9696/
        #description: Homepage is the best
    - Radarr:
        icon: radarr.svg
        href: http://nas.repina.eu:7878/
        #description: Homepage is the best
    - Sonarr:
        icon: sonarr.svg
        href: http://nas.repina.eu:8989/
        #description: Homepage is the best
    - Audiobookshelf:
        icon: audiobookshelf.svg
        href: http://nas.repina.eu:10223/
        #description: Homepage is the best
