---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

background:
  #image: https://images.unsplash.com/photo-1538435740860-67bd8f4e8eb8
  #image: https://images.unsplash.com/photo-1488295169303-659d6d9a5da5
  image: https://images.unsplash.com/photo-1520052205864-92d242b3a76b
  blur: none # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 75 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

headerStyle: clean
color: slate
theme: dark # or light
useEqualHeights: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey