---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

theme: light #dark, light
color: neutral #slate, gray, zinc, neutral, stone, amber, yellow, lime, green, emerald, teal, cyan, sky, blue, indigo, violet, purple, fuchsia, pink, rose, red, white
headerStyle: clean
iconStyle: theme # optional, defaults to gradient
disableCollapse: true
statusStyle: dot
hideVersion: true

maxGroupColumns: 5 # default is 4 for services, 6 for bookmarks, max 8
maxBookmarkGroupColumns: 6 # default is 6, max 8
# fullWidth: true

background:
  image: https://images.unsplash.com/photo-1532019333101-b0f43c16a912
  #image: https://images.unsplash.com/photo-1485841890310-6a055c88698a
  #image: https://images.unsplash.com/photo-1493382051629-7eb03ec93ea2
  blur: none # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 100 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

layout:
  Infrastructure:
    icon: mdi-server
  Networking:
    icon: mdi-lan
  Utilities:
    icon: mdi-tools
  Monitoring:
    icon: mdi-chart-timeline-variant
  Media:
    icon: mdi-multimedia
  Bookmarks:
    icon: mdi-star
    style: row
    columns: 2
