blueprint:
  name: Moccamaster Turn ON - Alarm sync
  author: juronja
  description: Turns on a smart plug at a specific time, for my coffee machine.
  domain: automation
  homeassistant:
    min_version: 2024.6.0
  input:
    # Phone Next Alarm Trigger Inputs
    offset:
      name: Offset time
      description: Set an offset time in h:m:s format.
      selector:
        time:

triggers:
  - trigger: time
    at:
      entity_id: sensor.pixel_6a_next_alarm
      offset: !input offset
    
conditions:
  - condition: time
    after: "03:00:00"
    before: "09:00:00"
  - condition: zone
    entity_id: person.polona_burnik
    zone: zone.home

actions:
  - action: switch.turn_on
    target:
      entity_id:
        - switch.moccamaster

mode: single
