blueprint:
  name: Moccamaster
  author: juronja
  description: Turns on a smart plug at a specific time, for my coffee machine.
  domain: automation
  input:
    turn_on_time:
      name: Turn On Time
      description: The time of day to turn on the smart plug (e.g., 07:00:00).
      selector:
        time:

trigger:
  - platform: time
    at: !input turn_on_time

action:
  - service: switch.turn_on
    target:
      entity_id: switch.moccamaster

mode: single