blueprint:
  name: Moccamaster
  author: juronja
  description: Turns on a smart plug at a specific time, for my coffee machine.
  domain: automation
  input:
    # Scheduled Time Trigger Inputs
    turn_on_time:
      name: Scheduled Turn On Time
      description: The time of day to turn on the smart plug (e.g., 07:00:00).
      selector:
        time:
    enable_time_trigger:
      name: Enable Scheduled Time Trigger
      description: Turn on to activate the trigger based on a fixed scheduled time.
      selector:
        boolean:
      default: false # Default to off

    # Phone Next Alarm Trigger Inputs
    enable_alarm_trigger:
      name: Enable Alarm Trigger
      description: Turn on to activate the trigger based on your phone's next alarm.
      selector:
        boolean:
      default: false # Default to off

    # Phone Screen On Trigger Inputs
    enable_screen_on_trigger:
      name: Enable Screen On Trigger
      description: Turn on to activate the trigger when your phone's screen turns on.
      selector:
        boolean:
      default: false # Default to off

trigger:
  # Trigger 1: Based on a fixed time (if 'turn_on_time' is provided)
  - platform: time
    at: !input turn_on_time
    id: time_based_trigger

  # Trigger 2: Based on the phone's next alarm (if 'phone_next_alarm_sensor' is provided)
  - platform: time
    at: sensor.pixel_8a_next_alarm
    id: alarm_based_trigger
    enabled: !input enable_alarm_trigger # This enables/disables the trigger itself

  # Trigger 3: Based on phone screen turning on (if 'phone_screen_on_sensor' is provided)
  - platform: state
    entity_id: binary_sensor.pixel_8a_interactive
    from: 'off'
    to: 'on'
    id: screen_on_based_trigger
    enabled: !input enable_screen_on_trigger # This enables/disables the trigger itself

action:
  - service: switch.turn_on
    target:
      entity_id: switch.moccamaster

mode: single