blueprint:
  name: Moccamaster Schedule
  author: juronja
  description: Turns on a smart plug at a specific time, for my coffee machine.
  domain: automation
  input:
    smart_plug_entity:
      name: Smart Plug Entity
      selector:
        entity:
          domain: switch # Assuming your smart plug is a switch entity
    turn_on_time:
      name: Turn On Time
      description: The time of day to turn on the smart plug (e.g., 07:00:00).
      selector:
        time:

trigger:
  - platform: time
    at: !input turn_on_time

action:
  - service: switch.turn_on
    target:
      entity_id: !input smart_plug_entity

mode: single