blueprint:
  name: Moccamaster
  author: juronja
  description: Turns on a smart plug at a specific time, for my coffee machine.
  domain: automation
  homeassistant:
    min_version: 2024.6.0
  input:


    # Phone Next Alarm Trigger Inputs
    enable_alarm_trigger:
      name: Enable Alarm Trigger
      description: Turn on to activate the trigger based on your phone's next alarm.
      selector:
        boolean:
      default: false # Default to off

triggers:
  - trigger: time
    at:
      entity_id: sensor.pixel_6a_next_alarm
      offset: "-00:10:00"
    
conditions:
  - condition: time
    after: "03:00:00"
    before: "09:00:00"
  - condition: zone
    entity_id: person.polona_burnik
    zone: zone.home

actions:
  - action: switch.turn_on
    target:
      entity_id:
        - switch.moccamaster

mode: single
