ubuntu:
  hosts:
    # ansible:
    #   ansible_host: ansible.lan
    #   ansible_ssh_private_key_file: ~/.ssh/id_ansible
    homelab:
      ansible_host: homelab.lan
      ansible_ssh_private_key_file: ~/.ssh/id_ubuntu-homelab
    hosting-prod:
      ansible_host: hosting-prod.lan
      ansible_ssh_private_key_file: ~/.ssh/id_hosting-prod
  vars:
    ansible_user: juronja
proxmox:
  hosts:
    pve-9700.lan
    # pve-4750g.lan
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_proxmoxes
    ansible_user: root