apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.shippingService.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.shippingService.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.shippingService.name }}
    spec:
      containers:
      - name: {{ .Values.shippingService.name }}
        image: {{ .Values.images.repository }}/{{ .Values.shippingService.name }}:{{ .Chart.AppVersion }}
        ports:
        - containerPort: {{ .Values.shippingService.port }}
        env:
        - name: PORT
          value: "50051"
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: {{ .Values.shippingService.port }}
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: {{ .Values.shippingService.port }}
        resources:
          {{- toYaml .Values.shippingService.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shippingService.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.shippingService.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.shippingService.port }}
      targetPort: {{ .Values.shippingService.port }}