serviceMonitor:
  enabled: true
  labels:
    release: monitoring
redisAddress: redis://redis-cart:6379
# env: {}
# - name: REDIS_PASSWORD
#   valueFrom:
#     secretKeyRef:
#       key: redis-password
#       name: redis-config-0.0.2